global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'self'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'secondary'
    static_configs:
      - targets: ['<secondary_ip>:9090']
